### ISSUE TITLE
Create code samples demonstrating account creation on the wiki via API for different cases

### ISSUE THREAD

**Issue by srish** [wikimedia/MediaWiki-Action-API-Code-Samples#10]
The account creation via the API is a complex process. It works differently in different cases: when creating an account for someone else, on a wiki with or without special authentication extensions installed. It might be good to develop code samples for different use cases and embed them here:  https://www.mediawiki.org/wiki/API:Account_creation. Three use cases to develop code samples for:
* A simple example, the case of a wiki where there aren't any special authentication extensions installed
* Complex example, the case of a wiki with special authentication extensions installed 
 * On a wiki with captcha enabled (Extension:ConfirmEdit)
 * On a wiki with two factor authentication enabled (Extension:OpenID or OATHAuth)

**Comment by tusharjindal353** [comment]
Mam I want to work on this issue.I am an outreachy applicant.Please help

**Comment by edyasikpo** [comment]
Hello, @srish I have made a  [pull request](https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples) for this issue. Kindly review for corrections. Thanks!

**Comment by silkypriya** [comment]
Hello @srish  I'd like to take this issue.

But I am facing problem in fetching openIdProvider required to select OpenID authentication.
The list of requests returned by API:Authmanagerinfo does not include definitions for both the OpenID extension.
Need help.Thank You!

**Comment by KaairaGupta** [comment]
hey @srish! i want to work on this issue, but am preoccupied with my university exams till 25th feb, can i please work on it after that?

**Comment by brendajerop** [comment]
I'm getting an "acct_creation_throttle_hit " error. Is there a workaround to this or should I wait another 24 hours before running my code again to check if the account creation was successful?

**Comment by edyasikpo** [comment]
Hello, @srish I need some clarifications. 
The **create_account_with_captcha.py** file is linked with the **create_account_form.html** file which provides a UI for account creation. 
Does this mean that I would have to remove the code that links **create_account_with_captcha.py** to  **create_account_form.html** so that the entire UI for account creation form would only come from the Authmanagerinfo module when I make the necessary changes to **create_account_with_captcha.py**?

**Comment by brendajerop** [comment]
Hello @silkypriya! I don't think wikipedia has an OpenId extension installed. Maybe test with another wiki that allows signing in with OpenID?

**Comment by brendajerop** [comment]
Hello @edyasikpo! From my understanding of the issue, it would be ideal to leave the create_account_with_captcha.py as it is, but  use its code to create another sample that accounts for a situation where both a captcha and openid extension are installed. 
In this case, I don't think it would cause any conflicts if you used the same html form for both samples, but it would be better to create a different html form because the two require slightly different inputs.

**Comment by silkypriya** [comment]
@brendajerop Okay,I will test with another wiki.Thank you for help.

**Comment by srish** [comment]
For everyone interested in working on this issue -- this task is mostly complete. What is remaining here is building the UI for [account creation form](https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/blob/2c6dd76af1e43d89fefabc13624d157681262685/python/templates/create_account_form.html) in [create_account_with_captcha.py](https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/blob/master/python/create_account_with_captcha.py) via [Authmanagerinfo](https://www.mediawiki.org/w/api.php?action=help&modules=query%2Bauthmanagerinfo) module. We are currently fetching only captcha fields but fetching other fields via the API would be a nice addition.  

https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/blob/2c6dd76af1e43d89fefabc13624d157681262685/python/create_account_with_captcha.py#L57

If you are interested in working on this issue, feel free to assign this task to yourself before starting to work on it.

**Comment by silkypriya** [comment]
Hey @srish can i work on this issue ?

**Comment by JoyLubega** [comment]
@srish Can I be assigned this issue

**Comment by edyasikpo** [comment]
Hello, @silkypriya @JoyLubega I believe @srish said that if anybody wants to work on this issue, he or she should assign the task to his or her self before working on it.
So at this point in time,  assign the task to yourself and start working on it before someone else does that, you don't need to ask for permission anymore. I hope you understand?

**Comment by mansiag** [comment]
@srish Could you please assign the issue to someone officially. So that everyone who has commented above do not work on it.

**Comment by SunitiJain** [comment]
hi! I am an outreachy applicant. I want to make contribution to the project. Please guide me. Thanks for help.

**Comment by mchesler613** [comment]
Hello, I am with Outreachy and am looking into how I can assist.

**Comment by SunitiJain** [comment]
Hi! Thanks for the reply.
I want to contribute in the project - *documentation improvement to the ~20
top 70 mosy viwes MesiaWiki Action API pages on wiki.*

Its my 1st open source contribute. Please guide me.

**Comment by ARsquare** [comment]
> For everyone interested in working on this issue -- this task is mostly complete. What is remaining here is building the UI for [account creation form](https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/blob/2c6dd76af1e43d89fefabc13624d157681262685/python/templates/create_account_form.html) in [create_account_with_captcha.py](https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/blob/master/python/create_account_with_captcha.py) via [Authmanagerinfo](https://www.mediawiki.org/w/api.php?action=help&modules=query%2Bauthmanagerinfo) module. We are currently fetching only captcha fields but fetching other fields via the API would be a nice addition.
> 
> [MediaWiki-Action-API-Code-Samples/python/create_account_with_captcha.py](https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/blob/2c6dd76af1e43d89fefabc13624d157681262685/python/create_account_with_captcha.py#L57)
> 
> Line 57 in [2c6dd76](/wikimedia/MediaWiki-Action-API-Code-Samples/commit/2c6dd76af1e43d89fefabc13624d157681262685)
> 
>  def get_captcha_fields(): 
> If you are interested in working on this issue, feel free to assign this task to yourself before starting to work on it.


Hey @srish, I am an outreachy applicant. I have been trying to work on this issue and am facing some ambiguity. Please clarify what fields exactly of the [account creation form](https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/blob/2c6dd76af1e43d89fefabc13624d157681262685/python/templates/create_account_form.html) are to be fetched from the API, or do we need to fetch all the fields and use in the form making it more generic instead of the hard-coding the the fields in the form itself. Thanks!!

**Comment by srish** [comment]
@ARsquare Hi! Fetch whatever fields you are able to retrieve from https://www.mediawiki.org/w/api.php?action=query&meta=authmanagerinfo&amirequestsfor=create to replace the corresponding account creation fields in the form. I think this will include all the fields but not one maybe: captcha-word input.

**Comment by megha070** [comment]
Hello! This is Megha Varshney. I found this project interesting hence would like to work on the same.

**Comment by brendajerop** [comment]
@megha070 This issue has already been assigned to @ARsquare :)

**Comment by megha070** [comment]
@brendajerop that's absolutely fine. Please assign another one to me.

**Comment by vaarigupta** [comment]
Hello, This is Vaari Gupta . I would like to work on this issue. How can I?
