### ISSUE TITLE
Refactor `create_account_with_captcha.py` code

### ISSUE THREAD

**Issue by srish** [wikimedia/MediaWiki-Action-API-Code-Samples#110]
There are some leftover issues from https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/pull/100#pullrequestreview-217481364 that need to be addressed (that pull request was accidentally merged by @srish and couldn't be reverted back easily).

**Comment by brendajerop** [comment]
@srish may I work on this then?:)

**Comment by ARsquare** [comment]
Sure! You can work on the issue... Since I am little busy with my exams.

**Comment by srish** [comment]
@brendajerop Go for it! :)
