### ISSUE TITLE
Reorganize README.md

### ISSUE THREAD

**Issue by srish** [wikimedia/MediaWiki-Action-API-Code-Samples#111]
Currently, [README.md](https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/blob/master/README) contain links to all Python files that live inside the `Python` directory. But, this repository is not just about Python files anymore and also include Javascript files. There might be PHP files too in the future.

Some ideas for improvements:
* There could be a logo of MediaWiki on the top in the README.
* All Python files could be linked from a README that lives in the Python directory.
* All Javascript files could be linked from a README that lives in the Javascript directory.
* If there is some magic way to reduce the number of lines in the current README that would be great. 
* The main README can then only have an overview of the modules or demo apps that are in the repo.
* Also, installation and contributing code samples section can be removed as they will be taken care of here: https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/pull/107.

**Comment by shivanshbindal9** [comment]
Hi @srish, can I work on this? 
Also, should the ```autogenerator.py``` file be moved out of the ```python``` folder to the root folder as it no longer generates ```python``` files only but also the ```javascript``` files and may be ```PHP``` files too in future ?

**Comment by srish** [comment]
@shivanshbindal9 yes, you are right! That file should be moved out of the `Python` folder to the root folder :)

**Comment by srish** [comment]
Referenced here https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/pull/114. Thanks @shivanshbindal9 for your work on this!
