### ISSUE TITLE
Make improvements to user contributions demo app

### ISSUE THREAD

**Issue by srish** [wikimedia/MediaWiki-Action-API-Code-Samples#112]
Some suggestions I made to improve the UserContributions demo app in https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/pull/89. 

Suggested changes are here in this comment:
https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/pull/89#pullrequestreview-213790739.

**Comment by brendajerop** [comment]
@srish Can I work on this?

**Comment by Jayprakash-SE** [comment]
I am working on that @srish ji.

**Comment by brendajerop** [comment]
@Jayprakash-SE okay:)

**Comment by srish** [comment]
Addressed in https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/pull/113 and https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/commit/82c58aedf171e67b8604a12a29013819ab4f19b8. 

Thanks @Jayprakash-SE for your work on this :)
