### ISSUE TITLE
Add an example to demonstrate the use of API:Links module to identify red links on a page

### ISSUE THREAD

**Issue by srish** [wikimedia/MediaWiki-Action-API-Code-Samples#37]
More in response to the question asked here: https://discourse-mediawiki.wmflabs.org/t/data-returned-by-the-query-api-does-not-say-if-a-link-is-a-red-link-or-not/1043.

It would be a cool use case of how API:Links module can also be used as a generator.

**Comment by hasinifoss** [comment]
Hi @srish I'd like to work on this issue.

**Comment by yatri1609** [comment]
Hey @srish can I work on this issue ?

**Comment by edyasikpo** [comment]
Hello, @srish  I have made a [pull request](https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples) for this issue. Kindly review for corrections. Thanks!

**Comment by kshitija08** [comment]
@srish Hello, I am an outreachy applicant. And I wish to work on some issues. But as this issue is taken up by @edyasikpo , I would like to work on different issue.

**Comment by SupriyaSupugade** [comment]
@srish, I have made a [Pull request](https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/pull/50) for this issue. Please review. Thanks.!

**Comment by SupriyaSupugade** [comment]
#50

**Comment by KaairaGupta** [comment]
hey @srish  can i work on this issue despite other people already submitting their pull requests??

**Comment by srish** [comment]
Thanks all for your interest in working on this issue! As @edyasikpo and @SupriyaSupugade are already working on this, please wait till we have other tickets available. In a couple of days, I will be opening more issues that you could look into! Check back again in a few days. Thanks for your patience! 

In the future, when there will be more tasks, it might be ideal if you assign yourself to a task first that you are interested in, and then start working on it. That way others know, that the task is already taken up.

**Comment by yatri1609** [comment]
@srish isn't it the case that once you comment on the issue you wish to work on and then you start working on it only after it is assigned to you? As I don't see that practice being followed here. Please have a look at it as I commented on this issue as I wanted to work on but others just sent a pull request without the task being assigned to them.

**Comment by srish** [comment]
@edyasikpo @SupriyaSupugade @brendajerop I've reviewed your pull requests! I don't like this approach, but I will only be able to accept one person's contribution. Whenever you are done incorporating the feedback, I will take a second look. But, don't worry, I will add more microtasks today.

@hasinifoss Yes, that's exactly how you would do it! 

@yatri1609 that's exactly what I'm referring to in https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/issues/37#issuecomment-466203063.

**Comment by hasinifoss** [comment]
@srish Thank you! I will send the PR with the above described implementation.

**Comment by edyasikpo** [comment]
Okay @srish Thanks for the feedback!

**Comment by brendajerop** [comment]
@srish Okay. Apologies for the uncouth behaviour

**Comment by srish** [comment]
@hasinifoss As others are already working on this issue, I encourage you to take a look at other microtasks now available: https://phabricator.wikimedia.org/T215682.

**Comment by RachealN** [comment]
@srish, I am Racheal  an outreachy applicant and I would love to contribute on issues you posted 2 days ego here https://phabricator.wikimedia.org/T215682.  but as i can see all tasks have been booked. Is it okay if i pick the one am interested in and contribute or ? how should go about this? am really confused. Thanks

**Comment by srish** [comment]
Thanks @brendajerop for your work on this! I've made some corrections in your Sandbox. You can now copy paste Example 2 from https://www.mediawiki.org/wiki/User:Jeropbrenda/Sandbox/API:Links#Example_2:_Fetch_missing_links and add it as a second example here https://www.mediawiki.org/wiki/API:Links!
