### ISSUE TITLE
Add sample code for blocking user to demonstrate the use of API:Block module 

### ISSUE THREAD

**Issue by silkypriya** [wikimedia/MediaWiki-Action-API-Code-Samples#53]
The link of action API:Block module is : https://www.mediawiki.org/wiki/API:Block
This page hasn't a code sample to demonstrate the use of API:Block.It is good to develop code sample for this.

**Comment by srish** [comment]
@silkypriya Thanks for your interest in the project! This project is all about creating code samples for various modules supported by the Action API pages. And, therefore it doesn't make sense to create an issue for each module. I am closing this task and the similar one you've added: https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/issues/55.

**Comment by silkypriya** [comment]
@srish I apologize for this, will take care in future.
