### ISSUE TITLE
Add sample code for send an email to demonstrate the use of API:Emailuser module

### ISSUE THREAD

**Issue by silkypriya** [wikimedia/MediaWiki-Action-API-Code-Samples#56]
An email can be sent to users who have a confirmed email address. The API:Emailuser module page hasn't a code sample to demonstrate this action.It is good to develop code sample for this.

The link of action API:Emailuser module is : https://www.mediawiki.org/wiki/API:Emailuser

**Comment by srish** [comment]
Same comment https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/issues/53#issuecomment-466194714 applies to this task.
