### ISSUE TITLE
filename not generic in modules.json 

### ISSUE THREAD

**Issue by shivanshbindal9** [wikimedia/MediaWiki-Action-API-Code-Samples#70]
Currently, in the modules.json file the ```filename``` key has .py extension in all instances. But when generating code for javascript and php the filenames extension should be .js and .php respectievly. So, it should be made generic so that it can be used with any of them.
I would like to take up this issue

**Comment by srish** [comment]
Addressed in #80. Thanks a lot @shivanshbindal9!!
